export const couponsData = [
  {
    name: "Holiday Sale",
    code: "HOLIDAY2023",
    discount: "15%",
    startDate: "Dec 1, 2023",
    endDate: "Dec 31, 2023",
    status: true,
  },
  {
    name: "New Year's Clearance",
    code: "CLEARANCE2023",
    discount: "$50 off",
    startDate: "Jan 1, 2024",
    endDate: "Jan 15, 2024",
    status: false,
  },
  {
    name: "Spring Savings",
    code: "SPRINGSALE",
    discount: "20%",
    startDate: "Mar 15, 2024",
    endDate: "Mar 31, 2024",
    status: true,
  },
  {
    name: "Flash Friday",
    code: "FLASHFRIDAY",
    discount: "10%",
    startDate: "Feb 7, 2024",
    endDate: "Feb 7, 2024",
    status: true,
  },
  {
    name: "Summer Spectacular",
    code: "SUMMER2024",
    discount: "$75 off",
    startDate: "Jun 1, 2024",
    endDate: "Jun 30, 2024",
    status: true,
  },
  {
    name: "Back to School",
    code: "SCHOOL2024",
    discount: "25%",
    startDate: "Aug 15, 2024",
    endDate: "Sep 5, 2024",
    status: false,
  },
  {
    name: "Fall Frenzy",
    code: "FALLFRENZY",
    discount: "12%",
    startDate: "Oct 1, 2024",
    endDate: "Oct 31, 2024",
    status: true,
  },
  {
    name: "Black Friday Madness",
    code: "BFM2024",
    discount: "30%",
    startDate: "Nov 29, 2024",
    endDate: "Nov 30, 2024",
    status: true,
  },
  {
    name: "Cyber Monday Special",
    code: "CYBERMONDAY",
    discount: "$100 off",
    startDate: "Dec 2, 2024",
    endDate: "Dec 2, 2024",
    status: true,
  },
  {
    name: "Year-End Clearance",
    code: "YEAREND2024",
    discount: "18%",
    startDate: "Dec 26, 2024",
    endDate: "Dec 31, 2024",
    status: false,
  },
];
