export interface productInterface {
  id?: number;
  name?: string;
  stars?: number;
  category?: string;
  price?: number;
  status?: number;
  sale?: number;
}

export const productsData: productInterface[] = [
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 1,
    name: "Smartphone X",
    stars: 4.2,
    category: "Electronics",
    price: 599.99,
    status: 1,
    sale: 15,
  },
  {
    id: 2,
    name: "Denim Jeans",
    stars: 3.8,
    category: "Clothing",
    price: 39.99,
    status: 0,
    sale: 10,
  },
  {
    id: 3,
    name: "Coffee Maker Pro",
    stars: 4.5,
    category: "Home & Kitchen",
    price: 129.99,
    status: 15,
    sale: 25,
  },
  {
    id: 4,
    name: "Wireless Headphones",
    stars: 4.0,
    category: "Electronics",
    price: 79.99,
    status: 100,
    sale: 12,
  },
  {
    id: 5,
    name: "Running Shoes",
    stars: 4.3,
    category: "Footwear",
    price: 59.99,
    status: 6,
    sale: 18,
  },
  {
    id: 6,
    name: "Blender Deluxe",
    stars: 4.7,
    category: "Home & Kitchen",
    price: 89.99,
    status: 1,
    sale: 20,
  },
  {
    id: 7,
    name: "Leather Wallet",
    stars: 4.1,
    category: "Accessories",
    price: 29.99,
    status: 0,
    sale: 8,
  },
  {
    id: 8,
    name: "LED Desk Lamp",
    stars: 4.6,
    category: "Home & Office",
    price: 49.99,
    status: 99,
    sale: 15,
  },
  {
    id: 9,
    name: "Fitness Tracker",
    stars: 4.4,
    category: "Fitness",
    price: 69.99,
    status: 1,
    sale: 14,
  },
  {
    id: 10,
    name: "Air Fryer",
    stars: 4.8,
    category: "Kitchen Appliances",
    price: 149.99,
    status: 1,
    sale: 30,
  },
  {
    id: 11,
    name: "Laptop Sleeve",
    stars: 4.2,
    category: "Electronics",
    price: 19.99,
    status: 1,
    sale: 10,
  },
  {
    id: 12,
    name: "Printed T-Shirt",
    stars: 3.5,
    category: "Clothing",
    price: 14.99,
    status: 0,
    sale: 5,
  },
  {
    id: 13,
    name: "Desk Organizer",
    stars: 4.6,
    category: "Home & Office",
    price: 34.99,
    status: 1,
    sale: 12,
  },
  {
    id: 14,
    name: "Yoga Mat",
    stars: 4.3,
    category: "Fitness",
    price: 24.99,
    status: 1,
    sale: 8,
  },
  {
    id: 15,
    name: "Toaster",
    stars: 4.0,
    category: "Kitchen Appliances",
    price: 39.99,
    status: 1,
    sale: 10,
  },
];
